# GITHUB OVERRIDES
# can't change these
# safe: true
# lsi: false
# github: [Repository metadata]
source: '.'
exclude: ['node_modules', 'grunt', 'Gemfile', 'Gemfile.lock', 'package.json', '*.scss', '*.coffee',]

# Build settings
markdown: kramdown
highlighter: pygments

# Site settings
title: 'iG Design & Publishing'
email: 'production@igdesign.ca'
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://igdesign.github.io" # the base hostname & protocol for your site


name: "iG Design & Publishing"
tagline: ""

address: 'PO Box 248'
city: 'Duncan'
province: 'BC'
postal: 'V9L 3X3'

location: '60 Ingram St. Suite #2'
location-postal: 'V9L 1N7'